# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VK Client. Web interaction practice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
  pod 'DynamicJSON'
  pod 'SnapKit', '~> 4.0'
  pod 'SDWebImage', '~> 5.0'
  pod 'PromiseKit', '~> 6.8'


  # Pods for VK Client. Web interaction practice

end
